### ISSUE TITLE
Upload du logo opérateur

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#1112]
Pour la génération V2 #986 des attestations, nous allons ajouter le logo de l'opérateur dans l'en-tête.

Le backend a les nouvelles fonctionnalités suivantes : 
- [x] upload du logo au format *PNG* dans les actions CRUD de l'opérateur (_create_, _update_)
- [x] création de la table `operator.thumbnails` et `LEFT JOIN` dans les méthode du repo concernées.
- [x] configuration du JSON Schema des actions opérateur pour accepter `"thumbnail": string`

#### Notes techniques

Le logo est stocké directement en base pour améliorer les performances de rendu de la génération du PDF qui est le cas d'usage actuel. La version stockée sur S3 prenait 1500ms en moyenne, alors que la version db prend 500ms. L'overhead par rapport à la génération sans logo est très faible.

Le champ `data` de la table `operator.thumbnails` est au format `bytea`. Le repository PG dans le service Operator assure la conversion du logo au format `base64` -> `hex` -> `binary` et l'inverse.  
**La taille maximale du logo ne peut excéder 2Mo**

Le frontend doit envoyer l'image au format PNG encodé en `base64`. Le format JPG n'est pas supporté.

### TODO frontend

- [x] Interface d'upload du fichier image (png ou jpg)
- [x] Recadrage de l'image
- [x] Réencodage en front ?
- [x] Envoie du PNG encodé en base64 sur les actions `create` ou `update`

**Comment by margot-sanchez** [comment]
Sur dev : 

- [ ] Chargement d'une image sur le profil administrateur
- [ ] Changement d'une image (note : le fait de cliquer sur changer et après enregistrer n'est pas excellent en termes d'expérience utilisateur)
- [ ] Génération d'une attestation
- [ ] Regarder une attestation Cannot GET /v2/certificates/pdf/146b3338-899f-449f-ae06-2f7ecfe3a2fc
