### ISSUE TITLE
Problème de données territoire

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#1190]
### SOUCIS

Sur la production, les champs "surface" et "population" ne sont pas remplis dans la base de données territoires.

### DONE

- [x] migration de `surface` en `bigint` (cf. Roura, 3902km²) avec re-création de `trip.list_view` qui dépend du champ surface
- [x] Commande `APP_POSTGRES_TIMEOUT=0 yarn workspace @pdc/proxy ilos geo:surfacepopulation` pour synchroniser la `surface*` et la `population`
- [x] La commande met à jour **UNIQUEMENT** les territoires ayant une géométrie
- [x] Commande `APP_POSTGRES_TIMEOUT=0 yarn workspace @pdc/proxy ilos geo:shape` pour mettre à jour les contours géo des territoires n'en n'ayant pas.
- [ ] Update trip.list pour que l'update soit rétroactive

:information_source: Les commandes peuvent être lancées plusieurs fois. Lancer la commande `geo:fetch` avant pour récupérer les contours manquants et pouvoir calculer la surface dans `geo:surfacepopulation`

\* La surface est calculée par `ST_Area(geo, true)` de PostGis qui calcule en **m²** à partir du contour géographique projeté sur une sphère. La surface est convertie en **km²**

### TODO 

Vérifier les contours géographiques d'une commune. 
Reprendre https://github.com/betagouv/preuve-covoiturage/tree/feat/territory_sync
et faire attention aux territoires custom

**Comment by margot-sanchez** [comment]
@gillesboisson est-ce que tu peux retrouver ton script ?

**Comment by nmrgt** [comment]
SyncTerritoryInseeCommand.ts

**Comment by margot-sanchez** [comment]
Fait à 80% profiter du chantier test pour faire les 20% qui restent.

**Comment by margot-sanchez** [comment]
Besoin d'un point d'étape.

**Comment by margot-sanchez** [comment]
@jonathanfallon prend le sujet. Objectif : pouvoir déposer à nouveau les jeux de données sur data.gouv avec le bon carroyage.

**Comment by jonathanfallon** [comment]
Voir si on peut récupérer les données de surface et territoire uniquement. Le reste de la synchro sera géré avec l'observatoire.

**Comment by jonathanfallon** [comment]
Fermé automatiquement par la PR. Réouverture pour test.

**Comment by margot-sanchez** [comment]
Testé le 05/07/2021 sur dev 👎 
![image](https://user-images.githubusercontent.com/15428433/124486542-ff76f980-ddad-11eb-8823-b0a372afe4f8.png)

**Comment by margot-sanchez** [comment]
Sur la prod 👍 mais ce n'est pas rétroactif. C'est à partir du déploiement du fix. 
![image](https://user-images.githubusercontent.com/15428433/124488105-c50e5c00-ddaf-11eb-865f-e818229d0fbb.png)

**Comment by nmrgt** [comment]
Il faut faire un update de trip.list.

**Comment by nmrgt** [comment]
fermé par chantier territoire
