### ISSUE TITLE
Master front sprint 30

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#1325]
### Sujet

Regroupement de l'ensemble des tickets bug + UI du sprint 30.
 
- [x] Recherche des campagnes - Nom + Territoire #1146 
- [x] Liste des campagnes en cours #1324
- [x] Disparition choix opérateur - export #1289
- [x] Disparition message d'erreur mot de passe faux #1292
- [x] Bug visuel sélection opérateur export #1203
- [x] Amélioration > Les trajets > Classe #1206
- [x] Ajouter un lien vers la documentation depuis l'app #1306
- [x] Filtre par commune #1326
- [x] #1339 Utilisateur découverte ne peut plus créer de campagne
- [x] #1340 Lancement de campagne
- [x] #1223 Simulation sur les derniers mois
- [x] CRUD nouvel utilisateur #1227 
- [x] Bouton "créer" un nouvel utilisateur #1330
