### ISSUE TITLE
Changer la logique de génération du trip_id

### ISSUE THREAD

**Issue by P3rceval** [betagouv/preuve-covoiturage#1748]
**Contexte**

Actuellement on regroupe des trajets sous un même `trip_id` si 2 trajets ont été effectués dans un intervalle de 2 heures pour une même personne.
cf https://github.com/betagouv/preuve-covoiturage/blob/dev/api/services/carpool/src/providers/CrosscheckRepositoryProvider.ts#L61

**TODO**

- [x]  Utiliser le champs `operator_journey_id` pour regrouper les trajets quand celui-ci est présent dans le payload envoyé par l'opérateur
- [x]  Garder la logique de regroupement actuelle en backup si pas de `operator_journey_id` et réduire l'interval à 30min
- [ ] Voir si modifier rétroactivement les trip_id est possible est n'a pas d'impact et implémenter la commande

**Comment by jonathanfallon** [comment]
Nous faisons ça aujourd'hui :

1. recherche par `operator_trip_id`
2. recherche par identity UUID dans une plage de +/- 2 heures

https://github.com/betagouv/preuve-covoiturage/blob/9790c13c6800638f5f0486184d2af733d592c3ea/api/services/carpool/src/providers/CrosscheckRepositoryProvider.ts#L33

Pour l'application rétroactive de du regroupement, ça ne me semble pas possible vu que les trajets ont été validés et incités. Il faudrait rejouer le `carpool:crosscheck` puis les campagnes ce qui ne me semble pas possible.

La plage de recherche de 4h semble un peu large en effet, 30 minutes semble pas mal. Il faudrait avoir un protocole de test qui nous permette d'évaluer les résultats de cette modification.

**Comment by jonathanfallon** [comment]
Plage configurée à +/- 10 minutes.
Rejeu complet des trajets de juin 2022 et des campagnes.
voir : https://hackmd.io/vu5x--GuSwSA3UVcZEfjRA?edit
