### ISSUE TITLE
Passage à Typescript 5

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#2102]
Typescript 5 + Node 16 permettent de mettre à jour notre `tsconfig.json` avec une compilation du JS plus moderne.

```[tasklist]
### TODO
- [ ] Passer en Typescript 5
- [ ] Changer le `tsconfig.json` à la racine avec des options à jour (voir ci-dessous)
- [ ] Passer les `tsconfig.json` des services et providers en relatifs
- [ ] Corriger le code `.ts`
- [ ] Voir comment on peut être plus stricts sur les typages (notamment supprimer les `noImplicitAny`)
```

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "lib": ["ES2021"],
    "module": "ES2022",
    "moduleResolution": "node",
    "target": "ES2021"
  }
}
```
