### ISSUE TITLE
Support du carpool v2 sur les cee

### ISSUE THREAD

**Issue by nmrgt** [betagouv/preuve-covoiturage#2474]
:information_source:  merci de marquer les parties de code carpool_v1 à supprimer avec le commentaire suivant (a minima).
Ça permet que l'IDE affiche les types, enums, fonctions, etc... en _deprecated_ et que l'on puisse les supprimer petit à petit.

```ts
/**
 * @deprecated [carpool_v2_migration]
 */
```

### `journey_id`

`journey_id` est un identifiant unique par demande CEE. -> migration vers carpool_v2._id

```[tasklist]
### Tasks
- [x] Ajouter une colonne `operator_journey_id`
- [x] Mettre à jour le seeder pour les tests d'intégration
- [x] Mettre à jour la création de `cee_applications` pour utiliser v2 puis aller chercher `carpool_id` V1 pour la rétro-compat
- [x] Remplir les anciennes données
```
