### ISSUE TITLE
Réactiver les migrations

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#2691]
Le pod de migration a été désactivé le 14/11/2024 pour débloquer les déploiements de l'API.
https://github.com/betagouv/preuve-covoiturage-infra/commit/5a7011095889c97b7177ca0c40f677fa545b4f0b

### TODO

- [ ] fixer les problèmes de certificats (dans le cluster uniquement)
- [ ]  remplacer le JSON stream par la std Deno pour régler le soucis d'import CommonJS
- [ ] réactiver le migrator sur l'infra dans `applications/api/deployment.tf`

![image](https://github.com/user-attachments/assets/3d2184f5-9e7d-402e-a68b-356dd1e1979b)
