### ISSUE TITLE
Suppression du numéro de téléphone impossible

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#378]
User connecté : Super admin (créé dans la V2)

Problème :
Une fois que le numéro de téléphone est renseigné, il n'est pas possible de le supprimer.

La requête envoyée n'envoie pas `phone` :
```json
{
	"id": 1570040131720,
	"jsonrpc": "2.0",
	"method": "user:patch",
	"params": {
		"_id": "5d94e87...",
		"patch": {
			"email": "jonathan.fallon@beta.gouv.fr",
			"firstname": "Jonathan",
			"lastname": "Fallon"
		}
	}
}
```

**TODO** envoyer `null` comme valeur pour le supprimer

- [x] patch du BACK pour accepter la valeur `null` dans l'objet `patch`
- [x] patch du FRONT pour envoyer `null`
- [ ] test dans l'interface

**Comment by margot-sanchez** [comment]
A tester par @margot-sanchez 1H00

**Comment by margot-sanchez** [comment]
Je suis super admin (sous chrome) 

1° cas d'usage : je modifie le numéro dans mon profil utilisateur

- Je modifie et fait mettre à jour.

- J'ai un message comme quoi le numéro est à jour.

- Je me déconnecte et me reconnecte le numéro a bien été changé

👍 
2° cas d'usage : je modifie le numéro d'un autre profil
- Je modifie et fait mettre à jour.

- J'ai un message comme quoi le numéro est à jour.

- Je me déconnecte et me reconnecte le numéro a bien été changé

👍
