### ISSUE TITLE
Utiliser SIRET à la place de SIREN + NIC

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#431]
Aujourd'hui, les organisations (opérateurs et territoires) utilisent SIREN + NIC. Cela fait 2 champs à remplir (et seulement 1 est obligatoire...).

Avoir seulement le SIREN peut poser des problèmes, notamment avec les administrations. (cf. Thomas)

> SIRET = SIREN + NIC (9 + 5 chiffres)

### TODO
- [x] [db] migrer les données des champs SIREN et NIC vers SIRET
- [x] [db] suppression des champs SIREN et NIC
- [x] [back] màj des schemas (create, patch)
- [x] [front] changer le champ SIREN et SIRET (validation à 14 chiffres)
- [x] [front] supprimer le champ NIC

**Comment by margot-sanchez** [comment]
Dépend de #395

**Comment by margot-sanchez** [comment]
3H00

**Comment by margot-sanchez** [comment]
Obligatoire dans le sprint 10

**Comment by margot-sanchez** [comment]
Reste à faire 
[ ] Mise à jour de la documentation
