### ISSUE TITLE
Route de vérification des preuves envoyées

### ISSUE THREAD

**Issue by jonathanfallon** [betagouv/preuve-covoiturage#783]
Dans le service acquisition, ajouter une route en GET /journeys/{journey_id} pour que les opérateurs puissent vérifier qu'une preuve est bien dans la table `acquisition.acquisitions`.

### TODO

- [x] `GET /journeys/:journey_id` dans le proxy
- [x] token auth
- [x] cookie auth
- [x] permissions update
- [x] `acquisition:status` action
- [x] acquisition find method in repo
- [x] error find method in repo
- [x] update public documentation (Gitbook)

Support des statuts

- [x] ok
- [x] canceled
- [x] expired
- [x] acquisition_error
- [x] normalization_error
- [x] fraudcheck_error

## Auth

- Application token (JWT)
- Cookie

## Codes d'erreur

Codes HTTP : 
- 200
- 401 (token rejeté)
- 403 (le token n'a pas la permission, il faut recréer une nouvelle application)
- 404 (pas de preuve ou journey_id n'appartenant pas à l'opérateur)

## Format de réponse

Succès
```json
{
	"id": 1,
	"jsonrpc": "2.0",
	"result": {
	    "journey_id": "string",
	    "status": "string",
	    "created_at": "ISODate"
	}
}
```

Erreur
```json
{
	"id": 1,
	"jsonrpc": "2.0",
	"error": {
	    "code": "number",
	    "data": "string",
	}
}
```

## Statuts possibles

```js
const status = [
  "acquisition_error", // received but not saved due to acquisition error
  "normalization_error", // processing error
  "fraudcheck_error", // fraudcheck detected
  "canceled", // cancelled by operator
  "expired", // sent but too late
  "ok", // everything is ok :)
]
```

## API publiques

- `GET /journeys/:journey_id` (token auth)
- `POST /rpc {method:"acquisition:status"}` (cookie auth)

La seconde API pourra être utilisée par le front-end pour développer une UI.

**Comment by margot-sanchez** [comment]
En mode quick fix dans un premier temps puis dans un second temps faire un vrai chantier avec du front aussi. Faire une petite route sympatoche ;)
