### ISSUE TITLE
Master chantier export 

### ISSUE THREAD

**Issue by margot-sanchez** [betagouv/preuve-covoiturage#957]
Spécifications disponibles[ ici](https://hackmd.io/w7WGuqtLQLyhzbFZcaE_vA)

Sous-tickets associés au chantier
- [x] Ajouter colonne numéro département export #857 
- [x] Pas de nom d'opérateur si export côté territoire ==> ajouter mention "non visible" #799
- [x] Ajouter colonne - campagne applicable #841
- [x] Ajout id utilisateur anonymisé dans l'export #953
- [x] Ajouter une colonne date et une colonne heure dans l'export #946
- [x] Export données côté opérateur #169
- [x] Export données - distance en KM - montants financiers en € #954
